import { createClient } from '@supabase/supabase-js';
import { BarChart3, FileText, FolderOpen, LayoutDashboard, LogOut, Package, Settings, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, Navigate, Route, Routes } from 'react-router-dom';
import { Button, PageIntro } from './components';
import './admin.css';

const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = url && key ? createClient(url, key) : null;
type Profile = { display_name: string; role: 'owner'|'editor'|'sales'|'viewer'; is_active: boolean };
const menu = [['','数据概览',LayoutDashboard],['products','产品管理',Package],['applications','应用管理',FolderOpen],['industries','行业管理',FolderOpen],['articles','文章管理',FileText],['media','图片与文件管理',FolderOpen],['inquiries','询盘管理',Users],['sample-requests','样品申请管理',Users],['seo','SEO 检查与预览',BarChart3],['settings','网站设置',Settings]] as const;

function Login({onSuccess}:{onSuccess:(profile:Profile)=>void}) {const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [message,setMessage]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase){setMessage('请先配置 VITE_SUPABASE_URL 与 VITE_SUPABASE_ANON_KEY。');return}const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error||!data.user){setMessage('登录未成功，请检查账号或密码。');return}const {data:profile}=await supabase.from('profiles').select('display_name,role,is_active').eq('id',data.user.id).single();if(!profile?.is_active){await supabase.auth.signOut();setMessage('该账号未被授予后台访问权限。');return}onSuccess(profile as Profile)};return <><PageIntro eyebrow="后台管理" title="登录后台">使用 Supabase Auth 登录；页面权限同时由数据库 RLS 强制执行。</PageIntro><section className="section"><form className="admin-login" onSubmit={submit}><label className="field"><span>邮箱</span><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label className="field"><span>密码</span><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label><Button type="submit">登录</Button>{message&&<p className="form-result">{message}</p>}</form></section></>}
function Dashboard({profile}:{profile:Profile}){const cards=[['今日询盘','连接 Supabase 后显示'],['样品申请','连接 Supabase 后显示'],['待审核文章','连接 Supabase 后显示'],['缺少依据的产品','连接 Supabase 后显示']];return <section className="admin-content"><p className="eyebrow">{profile.role} · {profile.display_name||'后台用户'}</p><h1>数据概览</h1><div className="metric-grid">{cards.map(([label,value])=><article key={label}><p>{label}</p><strong>{value}</strong></article>)}</div><article className="admin-note"><h2>上线前检查</h2><p>公开产品、应用和文章必须处于已发布且已审核状态；参数必须关联资料版本；询盘和附件仅通过无状态 API 写入。</p></article></section>}
function AdminPage({title,profile}:{title:string;profile:Profile}) {const canEdit=profile.role==='owner'||profile.role==='editor';const salesOnly=title.includes('询盘')||title.includes('样品');const allowed=salesOnly?['owner','sales','viewer'].includes(profile.role):canEdit||profile.role==='viewer';return <section className="admin-content"><p className="eyebrow">后台管理</p><h1>{title}</h1>{allowed?<><article className="admin-note"><h2>受 RLS 保护的数据视图</h2><p>{canEdit?'可创建、保存草稿、提交审核与发布。发布前需完成内容依据检查。':'当前角色为只读访问。'} 实际数据从 Supabase 读取，权限由数据库策略而非仅前端路由决定。</p></article>{canEdit&&<Button>新建待审核内容</Button>}</>:<p className="form-result">当前角色没有访问此模块的权限。</p>}</section>}
function Shell({profile,onLogout}:{profile:Profile;onLogout:()=>void}) {return <div className="admin-shell"><aside><Link className="brand" to="/"><span className="brand-mark">心</span>阳光心材料</Link><p>管理后台</p>{menu.map(([path,label,Icon])=><Link key={path} to={`/admin/${path}`}><Icon size={17}/>{label}</Link>)}<button onClick={onLogout}><LogOut size={17}/>退出登录</button></aside><main><Routes><Route index element={<Dashboard profile={profile}/>}/>{menu.slice(1).map(([path,label])=><Route path={path} key={path} element={<AdminPage title={label} profile={profile}/>}/>)}<Route path="*" element={<Navigate to="/admin" replace/>}/></Routes></main></div>}
export function Admin(){const [profile,setProfile]=useState<Profile|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getUser().then(async({data})=>{if(data.user){const {data:profile}=await supabase.from('profiles').select('display_name,role,is_active').eq('id',data.user.id).single();if(profile?.is_active)setProfile(profile as Profile)}setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(!session)setProfile(null)});return()=>subscription.unsubscribe()},[]);const logout=async()=>{await supabase?.auth.signOut();setProfile(null)};if(loading)return <section className="section"><div className="shell">正在验证登录状态…</div></section>;return profile?<Shell profile={profile} onLogout={logout}/>:<Login onSuccess={setProfile}/>}
