import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowRight, Check, ChevronRight, Download, FileText, Search, ShieldCheck, Sparkles } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useLocation, useParams } from 'react-router-dom';
import { applications, articles, products } from './content';
import { apiBase, inquirySchema, type InquiryForm } from './lib';
import { Button, Layout, PageIntro } from './components';
import { Admin } from './admin';
import { track } from './analytics';
import './styles.css';

const queryClient = new QueryClient();
const crumb = (label: string) => <nav className="crumb"><Link to="/">首页</Link><ChevronRight size={14}/><span>{label}</span></nav>;

function Home() { return <>
  <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">FUNCTIONAL MATERIALS · CHINA</p><h1>进口与国产功能材料<br/><em>应用解决方案</em></h1><p className="lede">面向中国制造企业，提供产品资料、材料选型、样品测试与应用支持。</p><div className="actions"><Link className="button primary" to="/products">浏览产品 <ArrowRight size={17}/></Link><Link className="button secondary" to="/applications">按应用找材料</Link></div><p className="hero-note"><ShieldCheck size={16}/> 公开信息以已审核资料为准</p></div><figure className="hero-visual"><img src={`${import.meta.env.BASE_URL}images/materials-hero.png`} alt="织物表面的水滴和功能材料应用示意图"/><figcaption>应用示意图</figcaption></figure></div></section>
  <section className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">从需求出发</p><h2>按客户问题找材料</h2></div><Link to="/applications">查看全部应用 <ArrowRight size={17}/></Link></div><div className="problem-grid">{applications.map((a,i)=><Link className="problem-card" to={`/applications/${a.slug}`} key={a.slug}><span>0{i+1}</span><h3>{a.question}</h3><ArrowRight size={19}/></Link>)}</div></div></section>
  <section className="section tonal"><div className="shell"><div className="section-head"><div><p className="eyebrow">精选入口</p><h2>重点产品</h2></div><Link to="/products">产品中心 <ArrowRight size={17}/></Link></div><div className="card-grid">{products.map(p=><ProductCard product={p} key={p.slug}/>)}</div></div></section>
  <section className="section"><div className="shell split"><div><p className="eyebrow">为什么选择阳光心材料</p><h2>把材料资料、验证与应用沟通连成一条清晰路径。</h2></div><div className="check-list"><p><Check/>围绕客户的基材、工艺与目标性能建立沟通</p><p><Check/>产品参数、认证与性能结论仅在审核后公开</p><p><Check/>从资料申请、样品测试到选型与报价持续跟进</p></div></div></section>
  <section className="section tonal"><div className="shell"><div className="section-head"><div><p className="eyebrow">技术资料与文章</p><h2>先理解问题，再进入测试</h2></div><Link to="/knowledge">阅读材料知识 <ArrowRight size={17}/></Link></div><div className="article-grid">{articles.map(a=><ArticleCard article={a} key={a.slug}/>)}</div></div></section>
  <CTA/>
</> }

function ProductCard({product}:{product:typeof products[number]}) { return <article className="product-card"><div className="tag-row"><span className="tag">{product.origin}</span><span className="pending">{product.status}</span></div><h3>{product.name}</h3><p>{product.summary}</p><div className="tag-row">{product.tags.map(t=><span className="soft-tag" key={t}>{t}</span>)}</div><Link to={`/products/${product.slug}`}>查看产品结构 <ArrowRight size={16}/></Link></article> }
function ArticleCard({article}:{article:typeof articles[number]}) { return <article className="article-card"><FileText size={22}/><p className="eyebrow">材料知识 · 待审核</p><h3>{article.title}</h3><p>{article.excerpt}</p><Link to={`/knowledge/${article.slug}`}>查看文章 <ArrowRight size={16}/></Link></article> }
function Products() { return <><PageIntro eyebrow="产品中心" title="不用先知道牌号，也能开始选材。">可按功能、应用和行业浏览。公开内容只呈现经审核允许公开的产品信息。</PageIntro><section className="section"><div className="shell"><div className="filter-row"><span>全部产品</span><span>功能</span><span>应用</span><span>行业</span></div><div className="card-grid">{products.map(p=><ProductCard product={p} key={p.slug}/>)}</div></div></section></> }
function ProductDetail() { const {slug=''}=useParams(); const p=products.find(x=>x.slug===slug); if(!p) return <NotFound/>; return <><section className="detail-head"><div className="shell">{crumb('产品中心')}<div className="tag-row"><span className="tag">{p.origin}</span><span className="pending">{p.status}</span></div><h1>{p.name}</h1><p className="lede">{p.summary}</p><div className="actions"><Link className="button primary" to={`/documents?product=${p.slug}`}><Download size={17}/>获取 TDS / SDS</Link><Link className="button secondary" to={`/sample?product=${p.slug}`}>申请样品</Link></div></div></section><section className="section"><div className="shell detail-grid"><aside><a href="#overview">产品介绍</a><a href="#specs">技术参数</a><a href="#applications">推荐应用</a><a href="#notice">注意事项</a></aside><div className="prose"><section id="overview"><h2>产品介绍</h2><p>本页面用于承载已审核产品资料。当前为内容结构示例，不构成对适用性、性能、认证或安全性的承诺。</p><h3>解决的客户问题</h3><p>请提交基材、现有工艺及目标性能，由阳光心材料协助进行初步资料匹配与测试沟通。</p></section><section id="specs"><h2>技术参数</h2><div className="data-empty">当前产品尚未录入经审核的公开参数。请联系获取。</div></section><section id="applications"><h2>推荐应用</h2><ul>{p.applications.map(x=><li key={x}>{x}</li>)}</ul></section><section id="notice"><h2>包装、储存与注意事项</h2><p>包装、储存、保质期、加工建议与注意事项以当前版本的已审核 TDS/SDS 或书面资料为准。</p></section></div></div></section><CTA product={p.name}/></> }
function Applications() { return <><PageIntro eyebrow="应用方案" title="围绕客户任务，组织材料选择。">每个应用页将围绕基材、加工方式、目标性能和验证项目展开；仅在资料支持后发布具体建议。</PageIntro><section className="section"><div className="shell application-list">{applications.map(a=><Link className="application-row" to={`/applications/${a.slug}`} key={a.slug}><span className="pending">{a.status}</span><div><h2>{a.name}</h2><p>{a.question} · {a.summary}</p></div><ArrowRight/></Link>)}</div></section></> }
function ApplicationDetail() { const {slug=''}=useParams(); const a=applications.find(x=>x.slug===slug); if(!a)return <NotFound/>; const p=products.find(x=>x.slug===a.relatedProduct); return <><section className="detail-head"><div className="shell">{crumb('应用方案')}<p className="eyebrow">待审核应用结构</p><h1>{a.name}</h1><p className="lede">{a.summary}</p></div></section><section className="section"><div className="shell prose narrow"><h2>客户问题</h2><p>{a.question}</p><h2>建议确认的信息</h2><ul><li>基材及制品结构</li><li>现有加工方式与可调整范围</li><li>目标性能、验证标准和使用条件</li></ul>{p&&<><h2>关联材料</h2><Link className="inline-card" to={`/products/${p.slug}`}>{p.name}<ArrowRight size={18}/></Link></>}<h2>验证项目</h2><p>验证项目必须由已审核资料、实际工艺和双方确认的测试条件共同确定。</p></div></section><CTA product={a.name}/></> }
function Knowledge() { return <><PageIntro eyebrow="材料知识" title="将技术问题说清楚。">内容用于帮助采购、研发与配方团队形成更完整的资料和测试沟通；所有文章发布前需人工审核。</PageIntro><section className="section"><div className="shell article-grid">{articles.map(a=><ArticleCard article={a} key={a.slug}/>)}</div></section></> }
function ArticleDetail(){const {slug=''}=useParams();const a=articles.find(x=>x.slug===slug);if(!a)return <NotFound/>;const p=products.find(x=>x.slug===a.productSlug);return <article className="article-detail"><div className="shell narrow">{crumb('材料知识')}<p className="eyebrow">待审核技术文章</p><h1>{a.title}</h1><p className="lede">{a.excerpt}</p><hr/><h2>内容依据提醒</h2><p>本文章是内容结构示例。发布前应补充并审核资料依据、适用边界、测试条件和关联内容，不能由 AI 自动发布。</p>{p&&<><h2>关联产品或应用</h2><Link className="inline-card" to={`/products/${p.slug}`}>{p.name}<ArrowRight size={18}/></Link></>}</div></article>}
function RequestPage({kind}:{kind:'documents'|'sample'|'inquiry'}) {const labels={documents:['技术资料申请','申请已审核的 TDS、SDS 或其他资料。'],sample:['样品申请','提交基材、工艺和目标性能，我们将协助进入样品沟通。'],inquiry:['选材与报价咨询','描述需求，获取初步材料选型和后续沟通。']} as const;return <><PageIntro eyebrow="需求提交" title={labels[kind][0]}>{labels[kind][1]}</PageIntro><section className="section"><div className="shell form-wrap"><InquiryForm kind={kind}/></div></section></>}
function InquiryForm({kind}:{kind:string}) { const {register,handleSubmit,formState:{errors,isSubmitting},reset}=useForm<InquiryForm>({resolver:zodResolver(inquirySchema),defaultValues:{services:kind==='documents'?['TDS/SDS']:kind==='sample'?['样品']:['技术咨询'],privacyAccepted:false}}); const [result,setResult]=useState(''); const onSubmit=async(values:InquiryForm)=>{setResult('');const res=await fetch(`${apiBase}/api/${kind==='sample'?'sample-requests':kind==='documents'?'document-requests':'inquiries'}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(values)});if(!res.ok)throw new Error('提交暂未成功，请稍后再试或通过联系方式咨询。');const data=await res.json();setResult(`已提交，编号：${data.request_id||data.inquiry_id||'待生成'}。我们将尽快跟进。`);reset();};return <form onSubmit={handleSubmit(onSubmit,()=>setResult('请检查必填项与隐私政策同意项。'))}><input className="honeypot" tabIndex={-1} autoComplete="off" {...register('website')}/><div className="form-grid"><Field label="姓名" error={errors.name?.message}><input {...register('name')}/></Field><Field label="公司名称" error={errors.company?.message}><input {...register('company')}/></Field><Field label="手机号" error={errors.phone?.message}><input inputMode="tel" {...register('phone')}/></Field><Field label="微信号（可选）"><input {...register('wechat')}/></Field><Field label="邮箱（可选）" error={errors.email?.message}><input type="email" {...register('email')}/></Field><Field label="所在省市" error={errors.provinceCity?.message}><input {...register('provinceCity')}/></Field><Field label="产品或应用" error={errors.productOrApplication?.message}><select {...register('productOrApplication')}><option value="">请选择</option>{[...products.map(p=>p.name),...applications.map(a=>a.name)].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="基材" error={errors.substrate?.message}><input {...register('substrate')}/></Field></div><Field label="当前问题" error={errors.currentProblem?.message}><textarea {...register('currentProblem')} rows={4}/></Field><Field label="目标性能" error={errors.targetPerformance?.message}><textarea {...register('targetPerformance')} rows={3}/></Field><Field label="所需服务" error={errors.services?.message}><div className="choices">{['TDS/SDS','样品','报价','技术咨询'].map(s=><label key={s}><input type="checkbox" value={s} {...register('services')}/>{s}</label>)}</div></Field><label className="privacy"><input type="checkbox" {...register('privacyAccepted')}/>我已阅读并同意<Link to="/privacy">隐私政策</Link></label><Button type="submit" disabled={isSubmitting}>{isSubmitting?'正在提交…':'提交需求'} <ArrowRight size={17}/></Button>{result&&<p className="form-result">{result}</p>}</form>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}{error&&<small>{error}</small>}</label>}
function SearchPage(){const q=new URLSearchParams(useLocation().search).get('q')||'';const results=[...products.map(x=>({type:'产品',name:x.name,url:`/products/${x.slug}`,text:x.summary})),...applications.map(x=>({type:'应用',name:x.name,url:`/applications/${x.slug}`,text:x.summary})),...articles.map(x=>({type:'文章',name:x.title,url:`/knowledge/${x.slug}`,text:x.excerpt}))].filter(x=>!q||`${x.name}${x.text}`.includes(q));return <><PageIntro eyebrow="站内搜索" title="查找产品、应用和技术文章。"><form className="search-form"><Search size={18}/><input defaultValue={q} name="q" placeholder="例如：防泼水、PVC、纸基阻隔"/><button>搜索</button></form></PageIntro><section className="section"><div className="shell results">{results.map(x=><Link key={x.url} to={x.url}><span>{x.type}</span><h2>{x.name}</h2><p>{x.text}</p></Link>)}{!results.length&&<p>未找到结果。可换用功能、基材或客户问题词搜索。</p>}</div></section></>}
function Plain({title,children}:{title:string;children:React.ReactNode}){return <><PageIntro eyebrow="阳光心材料" title={title}>{children}</PageIntro><section className="section"><div className="shell prose narrow">{title==='联系我们'?<><h2>联系入口</h2><p>微信、手机、邮箱、服务时间和地址统一从网站设置读取。当前为待配置状态。</p><Link className="button primary" to="/inquiry">咨询选材</Link></>:<><h2>说明</h2><p>本页面为上线前合规内容结构。正式发布前应由负责人员补充审核后的完整文本。</p></>}</div></section></>}
function CTA({product}:{product?:string}) {const inquiryUrl=product?`/inquiry?subject=${encodeURIComponent(product)}`:'/inquiry';return <section className="cta"><div className="shell"><div><p className="eyebrow">下一步</p><h2>不确定哪款材料适合？</h2><p>提交基材、工艺和目标性能，我们将协助进行初步选型。</p></div><div className="actions"><Link className="button primary" to={inquiryUrl}>咨询选材</Link><Link className="button secondary" to="/sample">申请样品</Link></div></div></section>}
function NotFound(){return <PageIntro eyebrow="404" title="未找到这个页面。">请返回首页，或从产品中心、应用方案和材料知识继续浏览。</PageIntro>}
function App(){const location=useLocation();useEffect(()=>{track('page_view',location.pathname)},[location.pathname]);return <Routes><Route path="/admin/*" element={<Admin/>}/><Route path="*" element={<Layout><Routes><Route path="/" element={<Home/>}/><Route path="/products" element={<Products/>}/><Route path="/products/:slug" element={<ProductDetail/>}/><Route path="/applications" element={<Applications/>}/><Route path="/applications/:slug" element={<ApplicationDetail/>}/><Route path="/knowledge" element={<Knowledge/>}/><Route path="/knowledge/:slug" element={<ArticleDetail/>}/><Route path="/documents" element={<RequestPage kind="documents"/>}/><Route path="/sample" element={<RequestPage kind="sample"/>}/><Route path="/inquiry" element={<RequestPage kind="inquiry"/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/about" element={<Plain title="关于阳光心材料">为国内企业客户提供功能材料的资料、选型、样品测试与应用支持。</Plain>}/><Route path="/contact" element={<Plain title="联系我们">选择适合的沟通入口，提交您的材料需求。</Plain>}/><Route path="/privacy" element={<Plain title="隐私政策">我们仅为处理您的需求而收集必要信息，并采取相应措施。</Plain>}/><Route path="/terms" element={<Plain title="使用条款">请在使用资料、网站内容和服务前阅读本条款。</Plain>}/><Route path="/disclaimer" element={<Plain title="产品资料与商标说明">产品资料以审核版本为准，相关商标归其权利人所有。</Plain>}/><Route path="*" element={<NotFound/>}/></Routes></Layout>}/></Routes>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={queryClient}><BrowserRouter basename={import.meta.env.BASE_URL}><App/></BrowserRouter></QueryClientProvider>);
