import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(process.cwd(), '../..');
const dist = path.join(root, 'apps/web/dist');
const base = process.env.VITE_BASE_PATH || '/';
const prefix = base.endsWith('/') ? base : `${base}/`;
const defaultProducts = [
  ['fluorine-free-textile-water-repellent','无氟织物防泼水材料｜飞织鞋面与户外面料应用','进口产品','用于需要表面疏水处理的织物应用；具体适用性、加工窗口和性能须以已审核资料与测试为准。'],
  ['pha-waterborne-paper-barrier','纸杯纸碗用 PHA 水性阻隔材料｜食品包装纸涂层','国产产品','面向纸基包装阻隔应用的材料方案结构示例，公开技术数据与合规依据待审核后发布。'],
  ['pvc-low-migration-plasticizer','PVC 低迁移功能增塑剂｜耐热低析出应用','进口产品','面向 PVC 制品应用的选材入口；迁移、析出与雾化等结论需基于具体配方和已审核资料。'],
  ['controlled-release-fertilizer-coating','控释肥用聚氨酯包衣剂｜滚筒包衣应用','国产产品','面向颗粒肥料包衣工艺的材料方案结构示例，实际工艺与性能需要结合现场验证。']
];
const defaultApps = [['knitted-upper-water-repellent','飞织鞋面防泼水处理','飞织鞋面如何实现表面防泼水？'],['food-paper-barrier','食品包装纸阻隔涂层','食品包装纸如何减少传统塑料淋膜？'],['pvc-low-migration','PVC 制品低迁移选材','PVC 如何降低迁移、析出和雾化？'],['fertilizer-drum-coating','控释尿素滚筒包衣','控释肥如何提高包衣均匀性？']];
const defaultArticles = [['how-to-verify-water-repellent-fabric','面料防泼水方案如何规划验证项目？','从基材、加工方式、目标性能和测试条件四个维度建立资料确认清单。'],['paper-barrier-material-selection','纸基包装阻隔材料选型前需要确认什么？','先明确制品结构、使用场景、涂布工艺和法规适用范围，再进入样品测试。']];
const contentFile = path.join(root, 'scripts', 'build-content.json');
const content = fs.existsSync(contentFile) ? JSON.parse(fs.readFileSync(contentFile, 'utf8')) : {};
const products = content.products?.length ? content.products.map(p => [p.slug, p.display_name, p.origin_type === 'imported' ? '进口产品' : '国产产品', p.summary || '请联系获取已审核资料。']) : defaultProducts;
const apps = content.applications?.length ? content.applications.map(a => [a.slug, a.name, a.customer_problem || a.summary || '请联系获取已审核应用资料。']) : defaultApps;
const articles = content.articles?.length ? content.articles.map(a => [a.slug, a.title, a.excerpt || '请联系获取已审核文章资料。']) : defaultArticles;
const esc = v => String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const layout = (title, description, body, schema) => `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} - 阳光心材料</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${prefix}${title==='首页'?'':locationPath(title)}"><meta property="og:title" content="${esc(title)} - 阳光心材料"><meta property="og:description" content="${esc(description)}"><link rel="icon" href="${prefix}favicon.svg"><script type="application/ld+json">${JSON.stringify(schema)}</script><style>body{font-family:-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif;margin:0;color:#172321;background:#f7f7f2;line-height:1.75}header,main,footer{max-width:1000px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;border-bottom:1px solid #d8ddd5}nav a{margin-left:16px;color:#315c50;text-decoration:none}h1{font-size:clamp(32px,5vw,58px);line-height:1.15;letter-spacing:-.04em}h2{margin-top:36px}.tag{display:inline-block;padding:4px 9px;border-radius:99px;background:#e5f0eb;color:#245842;font-size:13px}.pending{background:#fff5dd;color:#8a6726}.card{background:#fff;padding:20px;margin:16px 0;border:1px solid #e0e4dc;border-radius:16px}.cta{display:inline-block;background:#173f35;color:white;padding:12px 18px;border-radius:999px;text-decoration:none;margin:12px 8px 0 0}footer{margin-top:50px;background:#173f35;color:#d9e1dc;max-width:none;text-align:center}img{max-width:100%;border-radius:20px}</style></head><body><header><strong>阳光心材料</strong><nav><a href="${prefix}products/">产品中心</a><a href="${prefix}applications/">应用方案</a><a href="${prefix}knowledge/">材料知识</a><a href="${prefix}contact/">联系我们</a></nav></header><main>${body}</main><footer>阳光心材料 · 公开内容以已审核资料为准</footer></body></html>`;
const locationPath = title => ({'产品中心':'products/','应用方案':'applications/','材料知识':'knowledge/','关于阳光心材料':'about/','联系我们':'contact/','技术资料申请':'documents/','样品申请':'sample/','选材与报价咨询':'inquiry/','隐私政策':'privacy/','使用条款':'terms/','产品资料与商标说明':'disclaimer/','站内搜索':'search/'})[title] || '';
const brandSchema = { '@context':'https://schema.org', '@type':'Organization', name:'阳光心材料', url: prefix };
const write = (route, title, description, body, schema=brandSchema) => { const dir=route?path.join(dist,route):dist; fs.mkdirSync(dir,{recursive:true}); fs.writeFileSync(path.join(dir,'index.html'),layout(title,description,body,schema)); };
const links = (items, route) => items.map(i=>`<article class="card"><span class="tag pending">待审核</span><h2>${esc(i[1])}</h2><p>${esc(i[2]||i[3])}</p><a class="cta" href="${prefix}${route}/${i[0]}/">查看详情</a></article>`).join('');
write('', '首页','阳光心材料为中国制造企业提供产品资料、材料选型、样品测试与应用支持。',`<p class="tag">FUNCTIONAL MATERIALS · CHINA</p><h1>进口与国产功能材料应用解决方案</h1><p>面向中国制造企业，提供产品资料、材料选型、样品测试与应用支持。</p><a class="cta" href="${prefix}products/">浏览产品</a><a class="cta" href="${prefix}applications/">按应用找材料</a><h2>按客户问题找材料</h2>${apps.map(a=>`<article class="card"><h3>${esc(a[2])}</h3><a href="${prefix}applications/${a[0]}/">查看应用方案</a></article>`).join('')}<h2>重点产品</h2>${links(products,'products')}`);
write('products','产品中心','按功能、应用和行业浏览功能材料。',`<h1>不用先知道牌号，也能开始选材。</h1><p>可按功能、应用和行业浏览。公开内容只呈现经审核允许公开的产品信息。</p>${links(products,'products')}`);
for(const [slug,name,origin,summary] of products){const schema={'@context':'https://schema.org','@type':'Product',name,brand:{'@type':'Brand',name:'阳光心材料'},description:summary};write(`products/${slug}`,name,summary,`<p><span class="tag">${origin}</span> <span class="tag pending">待审核</span></p><h1>${esc(name)}</h1><p>${esc(summary)}</p><h2>产品介绍</h2><p>本页面用于承载已审核产品资料。当前为内容结构示例，不构成对适用性、性能、认证或安全性的承诺。</p><h2>技术参数</h2><p>当前产品尚未录入经审核的公开参数。请联系获取。</p><h2>资料与申请</h2><a class="cta" href="${prefix}documents/">获取 TDS / SDS</a><a class="cta" href="${prefix}sample/">申请样品</a><a class="cta" href="${prefix}inquiry/">咨询选材</a>`,schema)}
write('applications','应用方案','围绕基材、加工方式、目标性能和验证项目组织材料选择。',`<h1>围绕客户任务，组织材料选择。</h1><p>每个应用页围绕基材、加工方式、目标性能和验证项目展开；仅在资料支持后发布具体建议。</p>${links(apps,'applications')}`);
for(const [slug,name,question] of apps){write(`applications/${slug}`,name,question,`<p class="tag pending">待审核应用结构</p><h1>${esc(name)}</h1><h2>客户问题</h2><p>${esc(question)}</p><h2>建议确认的信息</h2><ul><li>基材及制品结构</li><li>现有加工方式与可调整范围</li><li>目标性能、验证标准和使用条件</li></ul><a class="cta" href="${prefix}sample/">申请样品</a><a class="cta" href="${prefix}inquiry/">咨询选材</a>`)}
write('knowledge','材料知识','围绕材料选型、应用工艺与测试方法的待审核知识内容。',`<h1>将技术问题说清楚。</h1><p>所有文章发布前需人工审核。</p>${links(articles,'knowledge')}`);
for(const [slug,title,excerpt] of articles){const schema={'@context':'https://schema.org','@type':'Article',headline:title,description:excerpt,publisher:{'@type':'Organization',name:'阳光心材料'}};write(`knowledge/${slug}`,title,excerpt,`<p class="tag pending">待审核技术文章</p><h1>${esc(title)}</h1><p>${esc(excerpt)}</p><h2>内容依据提醒</h2><p>本文章是内容结构示例。发布前应补充并审核资料依据、适用边界、测试条件和关联内容，不能由 AI 自动发布。</p>`,schema)}
for(const [route,title,desc] of [['documents','技术资料申请','申请已审核的 TDS、SDS 或其他资料。'],['sample','样品申请','提交基材、工艺和目标性能，我们将协助进入样品沟通。'],['inquiry','选材与报价咨询','描述需求，获取初步材料选型和后续沟通。'],['about','关于阳光心材料','为国内企业客户提供功能材料的资料、选型、样品测试与应用支持。'],['contact','联系我们','选择适合的沟通入口，提交您的材料需求。'],['privacy','隐私政策','我们仅为处理您的需求而收集必要信息。'],['terms','使用条款','请在使用资料、网站内容和服务前阅读本条款。'],['disclaimer','产品资料与商标说明','产品资料以审核版本为准，相关商标归其权利人所有。'],['search','站内搜索','查找产品、应用和技术文章。']])write(route,title,desc,`<h1>${title}</h1><p>${desc}</p><p>此静态页面可直接被搜索引擎读取；交互表单和站内搜索在浏览器端可用。</p><a class="cta" href="${prefix}inquiry/">提交需求</a>`);
write('404','未找到页面','请返回阳光心材料首页继续浏览。',`<h1>未找到这个页面。</h1><a class="cta" href="${prefix}">返回首页</a>`);
