-- 阳光心材料: content, leads, audit records and least-privilege RLS.
create extension if not exists pgcrypto;

create type public.user_role as enum ('owner','editor','sales','viewer');
create type public.content_status as enum ('draft','pending_review','published','archived');
create type public.origin_type as enum ('imported','domestic');
create type public.inquiry_stage as enum ('new','to_contact','needs_confirmed','sample_preparing','testing','quoted','won','on_hold','invalid');
create type public.document_access as enum ('public','form_required','approval_required','internal');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', role public.user_role not null default 'viewer', is_active boolean not null default true, created_at timestamptz not null default now());
create table public.product_categories (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, sort_order integer not null default 0, created_at timestamptz not null default now());
create table public.industries (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, summary text, status public.content_status not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.site_settings (key text primary key, value jsonb not null, is_public boolean not null default false, updated_at timestamptz not null default now());
create table public.media_assets (id uuid primary key default gen_random_uuid(), bucket text not null, object_path text not null unique, alt_text text, caption text, is_illustration boolean not null default false, width integer, height integer, mime_type text, bytes bigint, created_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), slug text not null unique, status public.content_status not null default 'draft', origin_type public.origin_type not null, origin_country text, original_brand text, original_grade text, show_origin_country boolean not null default false, show_original_brand boolean not null default false, show_original_grade boolean not null default false, display_name text not null, short_name text, summary text, description text, customer_problem text, substrates text[] not null default '{}', processing_methods text[] not null default '{}', packaging text, storage text, shelf_life text, precautions text, featured boolean not null default false, published_at timestamptz, reviewed_at timestamptz, review_source_summary text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint published_products_reviewed check (status <> 'published' or reviewed_at is not null));
create table public.product_features (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, label text not null, evidence_note text not null, sort_order integer not null default 0);
create table public.documents (id uuid primary key default gen_random_uuid(), product_id uuid references public.products(id) on delete set null, title text not null, document_type text not null check (document_type in ('tds','sds','report','other')), access_level public.document_access not null default 'internal', bucket text not null default 'private-documents', object_path text not null, version text, reviewed_at timestamptz, expires_at timestamptz, created_at timestamptz not null default now());
create table public.product_specifications (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, parameter_name text not null, typical_value text, min_value text, max_value text, unit text not null, test_method text, test_condition text, value_type text not null check (value_type in ('typical','range','guaranteed')), sort_order integer not null default 0, source_document_id uuid not null references public.documents(id) on delete restrict, reviewed_at timestamptz not null, created_at timestamptz not null default now());
create table public.applications (id uuid primary key default gen_random_uuid(), slug text not null unique, status public.content_status not null default 'draft', name text not null, summary text, customer_problem text, substrates text[] not null default '{}', processing_guidance text, validation_items text[] not null default '{}', published_at timestamptz, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint published_applications_reviewed check (status <> 'published' or reviewed_at is not null));
create table public.product_applications (product_id uuid not null references public.products(id) on delete cascade, application_id uuid not null references public.applications(id) on delete cascade, sort_order integer not null default 0, primary key(product_id,application_id));
create table public.articles (id uuid primary key default gen_random_uuid(), slug text not null unique, status public.content_status not null default 'draft', title text not null, excerpt text, cover_asset_id uuid references public.media_assets(id) on delete set null, body text not null default '', article_type text not null, primary_keyword text, secondary_keywords text[] not null default '{}', faq jsonb not null default '[]'::jsonb, seo_title text, seo_description text, published_at timestamptz, reviewed_at timestamptz, reviewer_id uuid references public.profiles(id), evidence_complete boolean not null default false, internal_evidence_note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint published_articles_reviewed check (status <> 'published' or (reviewed_at is not null and evidence_complete))); 
create table public.article_products (article_id uuid not null references public.articles(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, primary key(article_id,product_id));
create table public.faqs (id uuid primary key default gen_random_uuid(), owner_type text not null check (owner_type in ('product','application','article')), owner_id uuid not null, question text not null, answer text not null, sort_order integer not null default 0, reviewed_at timestamptz not null);
create table public.seo_metadata (id uuid primary key default gen_random_uuid(), entity_type text not null, entity_id uuid not null, title text not null, description text not null, canonical_path text not null, keywords text[] not null default '{}', synonyms text[] not null default '{}', forbidden_terms text[] not null default '{}', internal_link_targets text[] not null default '{}', unique(entity_type,entity_id));
create table public.inquiries (id uuid primary key default gen_random_uuid(), request_number text not null unique default ('INQ-' || to_char(now(),'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,6))), name text not null, company text not null, phone text not null, wechat text, email text, province_city text not null, product_or_application text not null, substrate text not null, current_problem text not null, target_performance text not null, monthly_usage text, services text[] not null, source_path text, utm jsonb not null default '{}'::jsonb, stage public.inquiry_stage not null default 'new', owner_id uuid references public.profiles(id), next_follow_up_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.sample_requests (id uuid primary key default gen_random_uuid(), inquiry_id uuid references public.inquiries(id) on delete set null, request_number text not null unique default ('SMP-' || to_char(now(),'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,6))), status public.inquiry_stage not null default 'new', created_at timestamptz not null default now());
create table public.document_requests (id uuid primary key default gen_random_uuid(), inquiry_id uuid references public.inquiries(id) on delete set null, document_id uuid references public.documents(id) on delete set null, request_number text not null unique default ('DOC-' || to_char(now(),'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,6))), status public.inquiry_stage not null default 'new', created_at timestamptz not null default now());
create table public.inquiry_attachments (id uuid primary key default gen_random_uuid(), inquiry_id uuid not null references public.inquiries(id) on delete cascade, bucket text not null, object_path text not null, file_name text not null, mime_type text not null, bytes bigint not null check (bytes between 1 and 10485760), created_at timestamptz not null default now());
create table public.inquiry_notes (id uuid primary key default gen_random_uuid(), inquiry_id uuid not null references public.inquiries(id) on delete cascade, author_id uuid not null references public.profiles(id), body text not null, created_at timestamptz not null default now());
create table public.inquiry_events (id uuid primary key default gen_random_uuid(), inquiry_id uuid not null references public.inquiries(id) on delete cascade, event_type text not null, payload jsonb not null default '{}'::jsonb, actor_id uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.content_revisions (id uuid primary key default gen_random_uuid(), entity_type text not null, entity_id uuid not null, revision jsonb not null, reason text, actor_id uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.publish_jobs (id uuid primary key default gen_random_uuid(), requested_by uuid references public.profiles(id), status text not null default 'queued' check(status in ('queued','running','success','failed')), external_run_id text, error_type text, created_at timestamptz not null default now(), finished_at timestamptz);
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index products_public_idx on public.products(status,published_at desc); create index applications_public_idx on public.applications(status,published_at desc); create index articles_public_idx on public.articles(status,published_at desc); create index inquiries_stage_idx on public.inquiries(stage,next_follow_up_at); create index product_specs_product_idx on public.product_specifications(product_id,sort_order); create index inquiry_phone_idx on public.inquiries(phone,created_at desc);

create or replace function public.current_role() returns public.user_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() and is_active=true $$;
create or replace function public.is_owner() returns boolean language sql stable security definer set search_path=public as $$ select public.current_role()='owner' $$;
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create trigger products_touch before update on public.products for each row execute function public.touch_updated_at(); create trigger applications_touch before update on public.applications for each row execute function public.touch_updated_at(); create trigger articles_touch before update on public.articles for each row execute function public.touch_updated_at(); create trigger inquiries_touch before update on public.inquiries for each row execute function public.touch_updated_at();

alter table public.profiles enable row level security; alter table public.product_categories enable row level security; alter table public.industries enable row level security; alter table public.site_settings enable row level security; alter table public.media_assets enable row level security; alter table public.products enable row level security; alter table public.product_features enable row level security; alter table public.documents enable row level security; alter table public.product_specifications enable row level security; alter table public.applications enable row level security; alter table public.product_applications enable row level security; alter table public.articles enable row level security; alter table public.article_products enable row level security; alter table public.faqs enable row level security; alter table public.seo_metadata enable row level security; alter table public.inquiries enable row level security; alter table public.sample_requests enable row level security; alter table public.document_requests enable row level security; alter table public.inquiry_attachments enable row level security; alter table public.inquiry_notes enable row level security; alter table public.inquiry_events enable row level security; alter table public.content_revisions enable row level security; alter table public.publish_jobs enable row level security; alter table public.audit_logs enable row level security;

create policy "published products readable" on public.products for select using(status='published'); create policy "published applications readable" on public.applications for select using(status='published'); create policy "published articles readable" on public.articles for select using(status='published'); create policy "public categories readable" on public.product_categories for select using(true); create policy "public industries readable" on public.industries for select using(status='published'); create policy "public settings readable" on public.site_settings for select using(is_public); create policy "public media readable" on public.media_assets for select using(true); create policy "published product features readable" on public.product_features for select using(exists(select 1 from public.products p where p.id=product_id and p.status='published')); create policy "published specs readable" on public.product_specifications for select using(exists(select 1 from public.products p where p.id=product_id and p.status='published')); create policy "published relations readable" on public.product_applications for select using(exists(select 1 from public.products p where p.id=product_id and p.status='published') and exists(select 1 from public.applications a where a.id=application_id and a.status='published')); create policy "published article products readable" on public.article_products for select using(exists(select 1 from public.articles a where a.id=article_id and a.status='published'));
create policy "staff reads profiles" on public.profiles for select using(auth.uid()=id or public.is_owner()); create policy "owner manages profiles" on public.profiles for all using(public.is_owner()) with check(public.is_owner());
create policy "content staff manage categories" on public.product_categories for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage industries" on public.industries for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "owner manages settings" on public.site_settings for all using(public.is_owner()) with check(public.is_owner()); create policy "content staff manage media" on public.media_assets for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage products" on public.products for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage features" on public.product_features for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage documents" on public.documents for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage specs" on public.product_specifications for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage applications" on public.applications for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage relations" on public.product_applications for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage articles" on public.articles for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage article relations" on public.article_products for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage faqs" on public.faqs for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor')); create policy "content staff manage seo" on public.seo_metadata for all using(public.current_role() in ('owner','editor')) with check(public.current_role() in ('owner','editor'));
create policy "sales read leads" on public.inquiries for select using(public.current_role() in ('owner','sales','viewer')); create policy "sales manage leads" on public.inquiries for update using(public.current_role() in ('owner','sales')) with check(public.current_role() in ('owner','sales')); create policy "sales read samples" on public.sample_requests for select using(public.current_role() in ('owner','sales','viewer')); create policy "sales manage samples" on public.sample_requests for update using(public.current_role() in ('owner','sales')) with check(public.current_role() in ('owner','sales')); create policy "sales read document requests" on public.document_requests for select using(public.current_role() in ('owner','sales','viewer')); create policy "sales manage document requests" on public.document_requests for update using(public.current_role() in ('owner','sales')) with check(public.current_role() in ('owner','sales')); create policy "sales manage notes" on public.inquiry_notes for all using(public.current_role() in ('owner','sales')) with check(public.current_role() in ('owner','sales')); create policy "sales manage events" on public.inquiry_events for all using(public.current_role() in ('owner','sales')) with check(public.current_role() in ('owner','sales')); create policy "owner reads attachments" on public.inquiry_attachments for select using(public.current_role() in ('owner','sales','viewer')); create policy "owner audits" on public.audit_logs for select using(public.is_owner()); create policy "staff reads publish jobs" on public.publish_jobs for select using(public.current_role() in ('owner','editor','viewer')); create policy "content revisions staff" on public.content_revisions for select using(public.current_role() in ('owner','editor','viewer'));

-- Private buckets: create in the Dashboard/CLI, never as public. Storage policies keep documents and lead files private.
insert into storage.buckets(id,name,public) values ('private-documents','private-documents',false),('private-attachments','private-attachments',false) on conflict(id) do nothing;
create policy "staff reads private storage" on storage.objects for select using(bucket_id in ('private-documents','private-attachments') and public.current_role() in ('owner','editor','sales','viewer'));
